version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: db_branchee
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-boot-network

volumes:
  pgdata:

networks:
  spring-boot-network:
    driver: bridge